networks:
    barbershop-network:
        driver: bridge

services:
    barbershop-customer:
        build:
            context: ./barbershop-customer
            dockerfile: Dockerfile
        container_name: barbershop-customer
        volumes:
            - ./barbershop-customer:/var/www/barbershop-customer
            - /var/www/barbershop-customer/node_modules
        ports:
            - 8000:8000
        restart: unless-stopped
        networks:
            - barbershop-network
    barbershop-admin:
        build:
            context: ./barbershop-admin
            dockerfile: Dockerfile
        container_name: barbershop-admin
        volumes:
            - ./barbershop-admin:/var/www/barbershop-admin
            - /var/www/barbershop-admin/node_modules
        ports:
            - 8001:8001
        restart: unless-stopped
        networks:
            - barbershop-network
    barbershop-api:
        build:
            context: ./barbershop-api
            dockerfile: Dockerfile
        container_name: barbershop-api
        volumes:
            - ./barbershop-api:/var/www/barbershop-api
        ports:
            - 9000:9000
        restart: unless-stopped
        networks:
            - barbershop-network
    barbershop-mysql:
        build: 
            context: ./docker/mysql
            dockerfile: Dockerfile
        container_name: barbershop-mysql
        volumes: 
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - 3307:3306
        restart: unless-stopped
        networks:
            - barbershop-network
        environment:
            MYSQL_ROOT_PASSWORD: root