networks:
  barbershop-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./barbershop_customer
      dockerfile: Dockerfile
    container_name: barbershop_customer
    volumes:
      - ./barbershop_customer:/var/www/frontend
      - /var/www/frontend/node_modules
    ports:  
      - 8000:8000
    restart: unless-stopped
    networks:
      - barbershop-network