networks:
    barbershop-network:
        driver: bridge

services:
    barbershop-customer:
        build:
            context: ./barbershop-customer
            dockerfile: Dockerfile
        container_name: barbershop-customer
        volumes:
            - ./barbershop-customer:/var/www/barbershop-customer
        command: >
            sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run dev -- --host=0.0.0.0 --port=8000"
        ports:
            - 8000:8000
        restart: unless-stopped
        networks:
            - barbershop-network
    barbershop-admin:
        build:
            context: ./barbershop-admin
            dockerfile: Dockerfile
        container_name: barbershop-admin
        command: >
            sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run dev -- --host=0.0.0.0 --port=8001"
        volumes:
            - ./barbershop-admin:/var/www/barbershop-admin
        ports:
            - 8001:8001
        restart: unless-stopped
        networks:
            - barbershop-network
    barbershop-api:
        build:
            context: ./barbershop-api
            dockerfile: Dockerfile
        container_name: barbershop-api
        command: >
            sh -c "if [ ! -d vendor ]; then composer install; fi && php artisan serve --host=0.0.0.0 --port=9000"
        volumes:
            - ./barbershop-api:/var/www/barbershop-api
        ports:
            - 9000:9000
        restart: unless-stopped
        networks:
            - barbershop-network
    barbershop-mysql:
        build: 
            context: ./docker/mysql
            dockerfile: Dockerfile
        container_name: barbershop-mysql
        volumes: 
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - 3307:3306
        restart: unless-stopped
        networks:
            - barbershop-network
        environment:
            MYSQL_ROOT_PASSWORD: cristiano